import type { Metadata } from "next";
import React from "react";
import ConvexClientProvider from "@/providers/ConvexClientProvider";
import "../styles/global.scss";
import { Toaster } from "sonner";
export const metadata: Metadata = {
  title: "distribution",
  description: "Generated by lldan",
  metadataBase: new URL("https://distribution.lldan.ru"),
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ConvexClientProvider>
          <main className="wrapper">{children}</main>
          <Toaster position="top-left" richColors />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
